[general]
color = "bright-red"
interval = 200
blink = true
bold = true

[position]
horizontal = "center"
vertical = "center"

[date]
fmt = "%A, %d %B %Y"
use_12h = true
utc = false
hide_seconds = false
